### ISSUE TITLE
Problems when functions on arrays f.ex. forEach are used

### ISSUE THREAD

**Issue by florianf** [fabiospampinato/proxy-watcher#2]
Hi,
first of all, thanks for the lib and the update!

I updated to the latest store.js and latest proxy-watcher, and now I have a strange problem. It seems the native forEach array function is bound / proxied by store, the following example breaks for me:

```
const data = store({

})

data.categoryList = [1, 2, 3]
data.objectTypes = [1, 2, 3]

data.categoryList.forEach(id => console.log(id))
data.objectTypes.forEach(id => console.log(id))
```
```
Uncaught Error: Duplicate object encountered, the same object is being referenced both at path "categoryList.forEach" and at path "objectTypes.forEach". Duplicate objects in a watched object are not supported.
    at checkChildPathDuplicate (make_traps.js?f91d:25)
    at setChildPath (make_traps.js?f91d:42)
    at eval (make_traps.js?f91d:97)
    at Object.trapWrapper [as get] (make_traps.js?f91d:49)
    at eval (MandatorStore.jsx?d6b7:142)
```

Versions:
"proxy-watcher": "^3.0.0",
"@fabiospampinato/store": "^1.3.1",

My opinion:
I would ignore functions completly in the store, plain old objects can be proxied, no functions, classes etc.

**Comment by fabiospampinato** [comment]
Functions need to be proxied too as they will in turn potentially retrieve and modify properties, if they are left unproxied we won't be able to detect those changes.

This is a bug, everything in the prototype should be ignored by that check 🤔. I'll probably address this later today or tomorrow.

**Comment by fabiospampinato** [comment]
Fixed, thanks for the report!
